apiVersion: apps/v1
kind: Deployment
metadata:
  name: runpod-autoscaler
  namespace: platform
  labels:
    app: runpod-autoscaler
    component: control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runpod-autoscaler
  template:
    metadata:
      labels:
        app: runpod-autoscaler
        component: control
    spec:
      serviceAccountName: runpod-autoscaler
      containers:
      - name: autoscaler
        image: registry.${INFRA_REGISTRY}/streaming-platform/control/runpod-autoscaler:latest
        ports:
        - containerPort: 8080
          name: metrics
        env:
        - name: RUNPOD_API_KEY
          valueFrom:
            secretKeyRef:
              name: runpod-secrets
              key: api-key
        - name: RUNPOD_INSTANCE_TYPE
          value: "NVIDIA RTX 6000 Ada Generation"  # Or RTX A6000, A100, etc.
        - name: RUNPOD_NETWORK_VOLUME_ID
          value: "volume-id-here"
        - name: RUNPOD_TEMPLATE_ID
          value: "template-id-here"
        - name: KUBERNETES_MASTER
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: master-url
        - name: KUBERNETES_CA
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: ca-cert
        resources:
          requests:
            cpu: "200m"
            memory: 256Mi
          limits:
            cpu: "1000m"
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runpod-autoscaler
  namespace: platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runpod-autoscaler
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: runpod-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: runpod-autoscaler
subjects:
- kind: ServiceAccount
  name: runpod-autoscaler
  namespace: platform
---
apiVersion: v1
kind: Secret
metadata:
  name: runpod-secrets
  namespace: platform
type: Opaque
data:
  api-key: <base64-encoded-runpod-api-key>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: platform
data:
  master-url: "https://kubernetes.default.svc.cluster.local:443"
  ca-cert: "<base64-encoded-ca-cert>"

