apiVersion: apps/v1
kind: Deployment
metadata:
  name: ome-transcoder
  namespace: media
  labels:
    app: ome-transcoder
    component: video-processing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ome-transcoder
  template:
    metadata:
      labels:
        app: ome-transcoder
        component: video-processing
    spec:
      priorityClassName: media-critical
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: workload-type
                operator: In
                values:
                - gpu
          - weight: 50
            preference:
              matchExpressions:
              - key: spot-enabled
                operator: In
                values:
                - "true"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ome-transcoder
              topologyKey: kubernetes.io/hostname
      containers:
      - name: ome
        image: registry.${INFRA_REGISTRY}/streaming-platform/media/ome:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: 4Gi
            nvidia.com/gpu: 1
          limits:
            cpu: "8"
            memory: 16Gi
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 50051
          name: grpc
        env:
        - name: CONF_PATH
          value: "/opt/ovenmediaengine/conf/Server.xml"
        - name: LOG_PATH
          value: "/var/log/ovenmediaengine"
        volumeMounts:
        - name: config
          mountPath: /opt/ovenmediaengine/conf
        - name: logs
          mountPath: /var/log/ovenmediaengine
        livenessProbe:
          httpGet:
            path: /metrics
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /metrics
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: ome-config
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ome-config
  namespace: media
data:
  Server.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Server version="9">
      <Name>${HostName}</Name>
      <Type>mediarouter</Type>
      <IP>*</IP>
      <Port>
        <Providers>
          <WebRTC>
            <Signalling>
              <Port>3333</Port>
              <TLSPort>3334</TLSPort>
            </Signalling>
          </WebRTC>
        </Providers>
        <Publishers>
          <HLS>
            <Port>80</Port>
            <TLSPort>443</TLSPort>
          </HLS>
          <MPEGTS>
            <Port>4000</Port>
            <MetaPort>4001</MetaPort>
          </MPEGTS>
        </Publishers>
      </Port>
      
      <Bind>
        <Publishers>
          <WebRTC>
            <Signalling>*:3333</Signalling>
            <SignallingTLS>*:3334</SignallingTLS>
          </WebRTC>
          <HLS>*:80, *:443</HLS>
          <MPEGTS>*:4000/*4001</MPEGTS>
        </Publishers>
      </Bind>
      
      <VirtualHosts>
        <VirtualHost>
          <Name>default</Name>
          <Domain>
            <Names>
              <Name>*</Name>
            </Names>
          </Domain>
          
          <Origins>
            <Origin>
              <Pass>
                <Scheme>ovt</Scheme>
                <Urls><Url>origin:9000</Url></Urls>
              </Pass>
            </Origin>
          </Origins>
          
          <Applications>
            <Application>
              <Name>live</Name>
              <Type>live</Type>
              
              <OutputProfiles>
                <OutputProfile>
                  <Name>bypass</Name>
                  <OutputStreamName>${OriginStreamName}</OutputStreamName>
                </OutputProfile>
                
                <!-- HLS outputs -->
                <OutputProfile>
                  <Name>hls</Name>
                  <OutputStreamName>${OriginStreamName}_hls</OutputStreamName>
                  <Encodes>
                    <Video>
                      <Codec>h264</Codec>
                      <Bitrate>3000000</Bitrate>
                      <Framerate>30</Framerate>
                      <Width>1920</Width>
                      <Height>1080</Height>
                      <Preset>faster</Preset>
                    </Video>
                    <Audio>
                      <Codec>aac</Codec>
                      <Bitrate>128000</Bitrate>
                      <Samplerate>48000</Samplerate>
                      <Channel>2</Channel>
                    </Audio>
                  </Encodes>
                  <HLS>
                    <Window>5</Window>
                    <SegmentDuration>2</SegmentDuration>
                    <SegmentCount>3</SegmentCount>
                  </HLS>
                </OutputProfile>
                
                <!-- AV1 output -->
                <OutputProfile>
                  <Name>av1</Name>
                  <OutputStreamName>${OriginStreamName}_av1</OutputStreamName>
                  <Encodes>
                    <Video>
                      <Codec>av1</Codec>
                      <Bitrate>2000000</Bitrate>
                      <Framerate>30</Framerate>
                      <Width>1920</Width>
                      <Height>1080</Height>
                      <Preset>faster</Preset>
                    </Video>
                    <Audio>
                      <Codec>opus</Codec>
                      <Bitrate>128000</Bitrate>
                      <Samplerate>48000</Samplerate>
                      <Channel>2</Channel>
                    </Audio>
                  </Encodes>
                  <HLS>
                    <Window>5</Window>
                    <SegmentDuration>2</SegmentDuration>
                    <SegmentCount>3</SegmentCount>
                  </HLS>
                </OutputProfile>
              </OutputProfiles>
              
              <Publishers>
                <HLS>
                  <SegmentDuration>2</SegmentDuration>
                  <Playlist>true</Playlist>
                </HLS>
              </Publishers>
            </Application>
          </Applications>
        </VirtualHost>
      </VirtualHosts>
    </Server>

