apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssai-adapter
  namespace: media
  labels:
    app: ssai-adapter
    component: ads
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ssai-adapter
  template:
    metadata:
      labels:
        app: ssai-adapter
        component: ads
    spec:
      priorityClassName: media-critical
      containers:
      - name: adapter
        image: registry.${INFRA_REGISTRY}/streaming-platform/media/ssai-adapter:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ADSERVER_URL
          value: "https://adserver.example.com/api"
        - name: DRM_PROXY_URL
          value: "http://drm-proxy.media.svc.cluster.local:80"
        - name: DRAGONFLY_ADDR
          value: "dragonfly-svc.data.svc.cluster.local:6379"
        resources:
          requests:
            cpu: "500m"
            memory: 1Gi
          limits:
            cpu: "2000m"
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ssai-adapter
  namespace: media
spec:
  selector:
    app: ssai-adapter
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP

