apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: platform
  labels:
    app: web-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
      - name: web
        image: registry.${INFRA_REGISTRY}/streaming-platform/clients/web:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: CDN_URL
          value: "https://streaming.example.com"
        - name: API_URL
          value: "https://api.example.com"
        resources:
          requests:
            cpu: "200m"
            memory: 256Mi
          limits:
            cpu: "1000m"
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: web-client
  namespace: platform
spec:
  selector:
    app: web-client
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: LoadBalancer

