_format_version: "3.0"

services:
  # Auth Service
  - name: auth-service
    url: http://auth-service:8080
    routes:
      - name: auth-routes
        paths:
          - /api/v1/auth
        methods:
          - GET
          - POST
          - PUT
          - DELETE
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Authorization
            - Content-Type
          credentials: true

  # Content Service
  - name: content-service
    url: http://content-service:8080
    routes:
      - name: content-routes
        paths:
          - /api/v1/content
        methods:
          - GET
          - POST
          - PUT
          - DELETE
    plugins:
      - name: cors
      - name: rate-limiting
        config:
          minute: 100
          hour: 1000
          policy: local
      - name: request-transformer
        config:
          add:
            headers:
              - "X-Service: content-service"

  # Search Service
  - name: search-service
    url: http://search-service:8080
    routes:
      - name: search-routes
        paths:
          - /api/v1/search
        methods:
          - GET
          - POST
    plugins:
      - name: cors
      - name: rate-limiting
        config:
          minute: 200
          policy: local

  # User Service
  - name: user-service
    url: http://user-service:8080
    routes:
      - name: user-routes
        paths:
          - /api/v1/users
        methods:
          - GET
          - PUT
          - DELETE
    plugins:
      - name: cors
      - name: jwt
        config:
          secret_is_base64: false
          uri_param_names:
            - token
          claims_to_verify:
            - exp

# Global plugins
plugins:
  - name: request-id
    config:
      header_name: X-Request-ID
      echo_downstream: true
  
  - name: correlation-id
    config:
      header_name: X-Correlation-ID
      echo_downstream: true

# Upstreams for load balancing
upstreams:
  - name: auth-service-upstream
    targets:
      - target: auth-service:8080
        weight: 100

  - name: content-service-upstream
    targets:
      - target: content-service:8080
        weight: 100

  - name: search-service-upstream
    targets:
      - target: search-service:8080
        weight: 100

